### ISSUE TITLE
KoAT runs out of memory on a trivial example

### ISSUE THREAD

**Issue by ffrohn** [draperlaboratory/kittel-koat#14]
KoAT runs out of memory on the following trivial ITS:

`(GOAL COMPLEXITY)`
`(STARTTERM (FUNCTIONSYMBOLS start))`
`(VAR)`
`(RULES`
`start() -> f()`
`)`

**Comment by jordanthayer** [comment]
I'll take a look.

**Comment by jordanthayer** [comment]
It's definitely on our end.  The original kittel-koat doesn't have the issue.

Two possibilities:

* The system is unary, and it's going through the special unary track we excised from kittel-koat to get weights working.
* My rewrite of the search loop inside of cint_meta is at fault

**Comment by jordanthayer** [comment]
Neither.  The instance is failing to parse.

**Comment by jordanthayer** [comment]
It was a bug in the arity-fixing code.  It didn't work for functions with arity 0.
