### ISSUE TITLE
KoAT fails to prove simple bound on weighted functions

### ISSUE THREAD

**Issue by codyroux** [draperlaboratory/kittel-koat#8]
Koat fails to find a bound on the following problem:

`(GOAL COMPLEXITY)
(STARTTERM (FUNCTIONSYMBOLS start))
(VAR env o5' o1)
(RULES
start(env, o5') -{0,0}> main_New_1(1 * env, 1 * o5') :|: 0 >= 0
main_New_1(o1, env) -{6,5 + o5'}> main_Return_8(1 * o1, 1 * env) :|: 0 >= 0 && 1 > 0 && 1 * o5' <= 1 + 1 * env && 1 <= 1 * o5'
)
`

The issue is the handling of "fresh" variables in the weights not appearing in the LHS. A solution would probably involve finding a bounding polynomial as a function of the LHS variables.

Probably related to issue #5.

**Comment by mischel** [comment]
I've written (and sent you) a patch addressing this problem the week before the engagement. It uses the `LSC` module to derive a local bound for free variables in weights. Anyway it is related to #5 and #7. So we should clarify the expected behavior for computing bounds.
